import type { Metadata } from "next";
import { lato, poppins } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Code Kenya | Gain Experience",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lato.variable} ${poppins.variable} antialiased`}
    >
      <body suppressHydrationWarning className={`${lato.className}`}>
        <div suppressHydrationWarning>{children}</div>
      </body>
    </html>
  );
}
